version: 2
jobs:
  build:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.4-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          DB_DATABASE: rails_tutorial
          DB_USERNAME: circleci-test-user
          DB_PASSWORD: circleci_password
          TZ: /usr/share/zoneinfo/Asia/Tokyo # Time Zoneを指定
      - image: circleci/mysql:5.7
        environment:
          # see also https://hub.docker.com/_/mysql/
          ## optional
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: rails_tutorial
          MYSQL_USER: circleci-test-user
          MYSQL_PASSWORD: circleci_password
          MYSQL_ROOT_HOST: '%'
          MYSQL_HOST: 127.0.0.1
    steps:
      - checkout

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v2-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache
      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      # Store yarn / webpacker cache
      # - save_cache:
      #    key: rails-demo-yarn-{{ checksum "yarn.lock" }}
      #    paths:
      #      - ~/.cache/yarn

      - run:
          name: Wait for DB
          # default port for mysql is 3306
          # see also https://circleci.com/docs/2.0/postgres-config/#using-dockerize
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m

      - run:
          name: Database setup
          # exec `rails db:migrate` locally to generate `db/schema.rb`!
          command: bin/rails db:schema:load --trace

      - run:
          name: run brakeman
          command: bundle exec brakeman -qz

      # Run rspec in parallel
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out test_results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      # Save test results for timing analysis
      - store_test_results:
          path: test_results
